package com.agile.asyoumean.model.externalmodel;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.4 Generated
 * source version: 2.1
 * 
 */
@WebFault(name = "AsYouMeanRequestException",
          targetNamespace = "http://www.turkcell.com.tr/webServices/AsYouMeanService")
public class AsYouMeanRequestException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2866427170163563989L;

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private String faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AsYouMeanRequestException(String message, String faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AsYouMeanRequestException(String message,
            String faultInfo,
            Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return returns fault bean: java.lang.String
     */
    public String getFaultInfo() {
        return faultInfo;
    }

}
