package com.agile.asyoumean.model.externalmodel;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.4 Generated
 * source version: 2.1
 * 
 */
@WebFault(name = "AsYouMeanRequestExeption", targetNamespace = "http://www.turkcell.com.tr/webServices/AsYouMeanService")
public class AsYouMeanRequestExeption extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private String faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public AsYouMeanRequestExeption(String message, String faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public AsYouMeanRequestExeption(String message, String faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: java.lang.String
	 */
	public String getFaultInfo() {
		return faultInfo;
	}

}
